version: '3.7'

services:
  front:
    build: ./
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      CI: "true"
      PORT: 80

  nginx:
    image: nginx:1.13.3
    restart: unless-stopped
    depends_on:
      - front
    ports:
      - ${APP_PORT}:80
    environment:
      BASE_URL: $BASE_URL
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./config/nginx/run.sh:/run.sh
    command: /bin/bash -c "/run.sh"
